# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vectra_vts', '0003_auto_20170110_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='gps',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vectra_vts.GpsDevice'),
        ),
    ]
