# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectra_vts', '0006_auto_20170111_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('A', 'assigned'), ('D', 'not assigned')], max_length=2, null=True),
        ),
    ]
