# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectra_vts', '0007_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('A', 'assigned'), ('D', 'not assigned')], max_length=2),
        ),
    ]
