# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vectra_vts', '0008_auto_20170111_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedto',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='assignedto',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vectra_vts.Driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectra_vts.GpsDevice'),
        ),
        migrations.DeleteModel(
            name='AssignedTo',
        ),
    ]
