# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vectra_vts', '0010_auto_20170112_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='gps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectra_vts.GpsDevice', unique=True),
        ),
    ]
